<div class="question-answer">
<h4><?php die(aaaaaa); echo $this->__('Answer and Question') ?></h4>

<form id="customer-form-question" method="post" action="<?php echo $this->getActionOfForm() ?>">
    <h2>Question<h2>
            <label class="required" for="firstname"><em style="color:red">*</em>&nbsp;<?php echo $this->__('Input Question'); ?></label>
            <div class="input-box">
                <textarea type="text" class="input-text required-entry" max-lenght="255" title="Question" name="question"></textarea>
            </div>
            <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Post Question') ?></span></span></button>
            </form>


            <div class="list-question">
                <?php
                
                $collection = Mage::getModel('qa/qa')->getCollection();
                $collection->getSelect()->group(array('question_id'));
                foreach ($collection as $item):
                    echo $item->getQuestion();
                    ?>
                <ul style="list-style-type: circle;margin-left: 40px;">
                    <?php 
                    $collectionAnswer = Mage::getModel('qa/qa')->getCollection()
                    ->addFieldToFilter('question_id',$item->getQuestion_id());
                    foreach ($collectionAnswer as $answer):?>
                    <?php if($answer->getAnswer()!=''):?>
                    <li><?php echo $answer->getAnswer();?>
                    </li>
                    <?php endif;?>
                        <?php endforeach;?>
                </ul>
                    <form method="post" action="<?php echo $this->getActionAnswerForm($item->getQuestion_id());?>">
                        <input type="hidden" name="questContent" value="<?php echo $item->getQuestion()?>"/>
                        <textarea type="text" class="input-text required-entry" max-lenght="255" title="Answer" name="answer"></textarea>
                        <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Post Answer') ?></span></span></button><br>
                    </form>
                <?php endforeach; ?>
            </div>
</div>


            <?php
            /*
              This will load one record from your database table.
              load(<module>_id) will load whatever ID number you give it.
             */
            /*
              $news = Mage::getModel('<module>/<module>')->load(1);
              echo $news->get<Module>Id();
              echo $news->getTitle();
              echo $news->getContent();
              echo $news->getStatus();
             */

            /*
              This block of code loads all of the records in the database table.
              It will iterate through the collection and the first thing it will do
              is set the Title to the current value of $i which is incremented each
              iteration and then echo that value back out.  At the very end it will
              save the entire collection.
             */
            /*
              $i = 0;

              $collection = Mage::getModel('<module>/<module>')->getCollection();
              $collection->setPageSize(5);
              $collection->setCurPage(2);
              $size = $collection->getSize();
              $cnt = count($collection);
              foreach ($collection as $item) {
              $i = $i+1;
              $item->setTitle($i);
              echo $item->getTitle();
              }

              $collection->walk('save');
             */

            /*
              This shows how to load one value, change something and save it.
             */

            /*
              $object = Mage::getModel('<module>/<module>')->load(1);
              $object->setTitle('This is a changed title');
              $object->save();
             */
            ?>
