<?php  if (Mage::getStoreConfig('facebook/facebook_general/enabled')) : ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<?php echo (Mage::getStoreConfig('facebook/facebook_general/locale') == 'auto') ? Mage::app()->getLocale()->getDefaultLocale() : Mage::getStoreConfig('facebook/facebook_general/locale'); ?>/all.js#xfbml=1&appId=<?php echo Mage::getStoreConfig('facebook/facebook_general/facebook_appid'); ?>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php endif; ?>
